### ISSUE TITLE
Tensorflow depencies issue

### ISSUE THREAD

**Issue by Arnold-git** [experience-ml/cartoonize#10]
Tried installing dependencies, got this error "ERROR: No matching distribution found for tensorflow==2.1.0 (from -r requirements.txt (line 5))"

Can you confirm that this is the right version of TensorFlow used

**Comment by tjdevWorks** [comment]
Yes it is the right version of tensorflow used, while it might work on other versions but we haven't tested it.
The python version on which I tested it is 3.7.4.
Check which python version you are using to see if there is a build available for tensorflow 2.1 for that python version.

You can try this colab notebook too https://colab.research.google.com/drive/1oDhMEVMcsRbe7bt-2A7cDsx44KQpQwuB?usp=sharing.

Do let me know if your issue is resolved.

**Comment by Arnold-git** [comment]
Thank you for responding.

currently using python 3.8.5, maybe that could be the possible reason for the issues. I will try to use python 3.7.4

**Comment by tjdevWorks** [comment]
The tensorflow install page https://www.tensorflow.org/install/pip says:  

> Python 3.8 support requires TensorFlow 2.2 or later.

I tested the app with tensorflow version 2.2 with GPU it works fine, you can go ahead and try with it too.
