### ISSUE TITLE
Video Size

### ISSUE THREAD

**Issue by hirenvadher954** [experience-ml/cartoonize#7]
Can we upload a video with more than 30 MB?

**Comment by nirajpandkar** [comment]
Hey! You can by changing the limit in the HTML page if you have a local instance running! Here's the line which limits the upload on the frontend - https://github.com/experience-ml/cartoonize/blob/master/templates/index_cartoonized.html#L409

And if you want to change the video length - https://github.com/experience-ml/cartoonize/blob/master/config.yaml#L5

We have limited it so that we can keep the cost of running to a minimum while providing a taste of the video cartoon conversion. 

Thanks for checking out and sorry for a late reply :)

**Comment by hirenvadher954** [comment]
> Hey! You can by changing the limit in the HTML page if you have a local instance running! Here's the line which limits the upload on the frontend - https://github.com/experience-ml/cartoonize/blob/master/templates/index_cartoonized.html#L409
> 
> And if you want to change the video length - https://github.com/experience-ml/cartoonize/blob/master/config.yaml#L5
> 
> We have limited it so that we can keep the cost of running to a minimum while providing a taste of the video cartoon conversion.
> 
> Thanks for checking out and sorry for a late reply 👍
